# Steps in Neural Network -
- **Forward Pass**: Compute *loss* at the end of Neural Network (NN)
- Compute the local gradients
- **Backward Pass**: Compute *derivative of loss* w.r.t. all the weights and biases in the NN - using chain rule

<p align="center">
Process:
</p>
<p align="center">
<img src="../images/Backprop_process.png" style="width:450px;height:250px;">
</p>
<p align="center">
Example:
</p>

<p align="center">
<img src="../images/Backprop_example.png" style="width:450px;height:250px;">
</p>

Pic credits - The Python Engineer YT channel

In [1]:
# Lets try the example out
import torch
x = torch.tensor(1.)
y = torch.tensor(2.)
w = torch.tensor(1., requires_grad=True)

# forward pass for the linear regression problem
y_hat = w * x
loss = (y_hat - y)**2
print('Loss:',loss)

# backward pass
loss.backward()
print(w.grad)

# This was one iteration, 
# Update weights and repeat the forward and back prop till you get optimal w

Loss: tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


#### Back Propogation Using Pytorch

y=x^2

In [2]:
x=torch.tensor(4.0,requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
print(x.grad)

None


In [5]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
#### Back propogation y=2*x
y.backward()

In [7]:
print(x.grad)

tensor(8.)


## With Matrix
### Example 1

In [8]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [9]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [10]:
### y=x**3+x**2
### y=3x**2+2x--->
y=torch_input**3+torch_input**2

In [11]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [12]:
z=y.sum()

In [13]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [14]:
z.backward() #y.backward() won't work as it requres to be a scalar

In [15]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

### Example 2

In [18]:
torch_input2 = torch.tensor([[2,6],[3,7],[9,8]],requires_grad=True, dtype=torch.float64)
torch_input2

tensor([[2., 6.],
        [3., 7.],
        [9., 8.]], dtype=torch.float64, requires_grad=True)

In [19]:
# y = log(x)
# y' = 1/x
y = torch.log(torch_input2)
y

tensor([[0.6931, 1.7918],
        [1.0986, 1.9459],
        [2.1972, 2.0794]], dtype=torch.float64, grad_fn=<LogBackward0>)

In [20]:
z = y.sum()
z.backward()

In [22]:
torch_input2.grad

tensor([[0.5000, 0.1667],
        [0.3333, 0.1429],
        [0.1111, 0.1250]], dtype=torch.float64)

In [23]:
1/torch_input2

tensor([[0.5000, 0.1667],
        [0.3333, 0.1429],
        [0.1111, 0.1250]], dtype=torch.float64, grad_fn=<MulBackward0>)