### Pytorch Tutorial
#### Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.
In many cases tensors are used as a replacement for NumPy to use the power of GPUs. GPUs are way more faster for all operations, matrix operations etc. than a CPU. The main source for GPUs are CUDA by NVIDIA. Tensors can use CUDA to use the GPU, but NumPy arrays are written for CPUs. 

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
torch.__version__

'1.12.0'

In [3]:
import numpy as np

In [4]:
lst=[3.,4,5,6]
arr=np.array(lst)

In [5]:
print(lst, arr) # We can see arr converts everything to float unlike the list

[3.0, 4, 5, 6] [3. 4. 5. 6.]


In [6]:
arr.dtype

dtype('float64')

In [7]:
lst=[3,4,5,6]
arr=np.array(lst)

### Convert Numpy To Pytorch Tensors

In [8]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [9]:
### Indexing similar to numpy
tensors[2]

tensor(5)

In [10]:
tensors[1:4]

tensor([4, 5, 6])

In [11]:
#### Advantage/Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [12]:
tensors

tensor([  3,   4,   5, 100])

In [13]:
arr

array([  3,   4,   5, 100])

In [14]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [15]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[  3   4   5 100]


In [16]:
t = torch.tensor([3.,4,5]) # Similar to numpy arrays, tensors also convert all the elements to the highest priority data type in the tensor

In [17]:
t.dtype # default dtype for numbers with decimals: 3.0, 4.2 etc.

torch.float32

In [18]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [21]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [22]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

Tensors, also like numpy arrays, need to have same number of elements 'a' per row and same number of elements 'b' per column (unlike lists)

### Converting Tensors to Numpy

In [23]:
tensors

tensor([  3,   4,   5, 100])

In [24]:
new_arr = tensors.numpy() # Both the tensor and numpy array will point to the same memory location in the CPU (Not for GPU)
print(new_arr)
print(type(new_arr))

[  3   4   5 100]
<class 'numpy.ndarray'>


In [25]:
tensors.add_(1)
print(tensors)
print(new_arr)

tensor([  4,   5,   6, 101])
[  4   5   6 101]


### Arithmetic Operation

#### Addition

In [26]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [27]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [28]:
c=torch.zeros(3) #same shape is required

In [29]:
torch.add(a,b,out=c) #c must be of same shape as a and b

tensor([ 7.,  9., 11.])

In [30]:
c

tensor([ 7.,  9., 11.])

In [31]:
b.add_(a) # _ is inplace addition: b is changed to b+a
print(b)

tensor([ 7.,  9., 11.])


In [32]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [33]:
### tensor[7,9,15]
torch.add(a,b).sum() #sum(torch.add(a,b)) - will also work

tensor(27.)

#### Subtraction

In [34]:
a - b

tensor([-1., -1., -1.])

In [35]:
c = torch.sub(a,b)
print(c)

tensor([-1., -1., -1.])


In [36]:
c = torch.zeros(3)
torch.sub(a,b, out=c)

tensor([-1., -1., -1.])

In [37]:
b.sub_(a) # b = b - a
print(b)

tensor([1., 1., 1.])


#### For multiplication and division
- `torch.mul` and `torch.div` is used for element-wise multiplication and division, similar to `*` and `/`
- `a.mul_(b)` is for implace multiplication, similiar to `a = a * b`
- `a.div_(b)` is for implace multiplication, similiar to `a = a / b`

### Slicing

In [38]:
a = torch.rand(5,3)
print(a)

tensor([[0.4066, 0.9277, 0.5862],
        [0.6793, 0.4024, 0.1121],
        [0.3090, 0.0849, 0.9140],
        [0.2457, 0.8656, 0.9987],
        [0.4261, 0.8874, 0.5731]])


In [39]:
print(a[:,0]) # All rows and column 1

tensor([0.4066, 0.6793, 0.3090, 0.2457, 0.4261])


In [40]:
print(a[1,:]) # Row 2 and all columns

tensor([0.6793, 0.4024, 0.1121])


In [41]:
print(a[0:2,1])

tensor([0.9277, 0.4024])


`.item()` is used is tensor has only one value in it.

<span style="color: red;">Cannot be used if there is more than 1 value</span>.

In [42]:
print(a[1,2])
print(a[1,2].item())

tensor(0.1121)
0.11210417747497559


### Reshaping Tensors

`.reshape()` or `.view()` is used to reshape tensors

In [43]:
a = torch.rand(8,8)
print(a)

tensor([[0.9826, 0.7057, 0.4725, 0.5816, 0.1636, 0.2196, 0.8620, 0.4628],
        [0.6589, 0.4870, 0.9997, 0.5431, 0.7703, 0.2417, 0.3230, 0.6452],
        [0.5115, 0.5316, 0.7312, 0.6976, 0.4326, 0.5961, 0.5460, 0.3598],
        [0.4004, 0.4848, 0.0859, 0.1078, 0.2560, 0.1734, 0.7836, 0.5910],
        [0.4561, 0.6876, 0.0162, 0.1736, 0.4072, 0.4348, 0.3791, 0.9949],
        [0.6514, 0.0893, 0.0150, 0.7559, 0.6124, 0.8414, 0.7062, 0.7631],
        [0.7246, 0.1353, 0.6749, 0.0330, 0.7088, 0.1843, 0.4360, 0.4048],
        [0.9638, 0.7500, 0.8151, 0.9616, 0.0503, 0.0070, 0.4145, 0.2156]])


In [44]:
a.reshape(64)

tensor([0.9826, 0.7057, 0.4725, 0.5816, 0.1636, 0.2196, 0.8620, 0.4628, 0.6589,
        0.4870, 0.9997, 0.5431, 0.7703, 0.2417, 0.3230, 0.6452, 0.5115, 0.5316,
        0.7312, 0.6976, 0.4326, 0.5961, 0.5460, 0.3598, 0.4004, 0.4848, 0.0859,
        0.1078, 0.2560, 0.1734, 0.7836, 0.5910, 0.4561, 0.6876, 0.0162, 0.1736,
        0.4072, 0.4348, 0.3791, 0.9949, 0.6514, 0.0893, 0.0150, 0.7559, 0.6124,
        0.8414, 0.7062, 0.7631, 0.7246, 0.1353, 0.6749, 0.0330, 0.7088, 0.1843,
        0.4360, 0.4048, 0.9638, 0.7500, 0.8151, 0.9616, 0.0503, 0.0070, 0.4145,
        0.2156])

In [45]:
a.reshape(16,-1) # if we put -1, it automatically captures the required number

tensor([[0.9826, 0.7057, 0.4725, 0.5816],
        [0.1636, 0.2196, 0.8620, 0.4628],
        [0.6589, 0.4870, 0.9997, 0.5431],
        [0.7703, 0.2417, 0.3230, 0.6452],
        [0.5115, 0.5316, 0.7312, 0.6976],
        [0.4326, 0.5961, 0.5460, 0.3598],
        [0.4004, 0.4848, 0.0859, 0.1078],
        [0.2560, 0.1734, 0.7836, 0.5910],
        [0.4561, 0.6876, 0.0162, 0.1736],
        [0.4072, 0.4348, 0.3791, 0.9949],
        [0.6514, 0.0893, 0.0150, 0.7559],
        [0.6124, 0.8414, 0.7062, 0.7631],
        [0.7246, 0.1353, 0.6749, 0.0330],
        [0.7088, 0.1843, 0.4360, 0.4048],
        [0.9638, 0.7500, 0.8151, 0.9616],
        [0.0503, 0.0070, 0.4145, 0.2156]])

In [46]:
a.view(16,-1)

tensor([[0.9826, 0.7057, 0.4725, 0.5816],
        [0.1636, 0.2196, 0.8620, 0.4628],
        [0.6589, 0.4870, 0.9997, 0.5431],
        [0.7703, 0.2417, 0.3230, 0.6452],
        [0.5115, 0.5316, 0.7312, 0.6976],
        [0.4326, 0.5961, 0.5460, 0.3598],
        [0.4004, 0.4848, 0.0859, 0.1078],
        [0.2560, 0.1734, 0.7836, 0.5910],
        [0.4561, 0.6876, 0.0162, 0.1736],
        [0.4072, 0.4348, 0.3791, 0.9949],
        [0.6514, 0.0893, 0.0150, 0.7559],
        [0.6124, 0.8414, 0.7062, 0.7631],
        [0.7246, 0.1353, 0.6749, 0.0330],
        [0.7088, 0.1843, 0.4360, 0.4048],
        [0.9638, 0.7500, 0.8151, 0.9616],
        [0.0503, 0.0070, 0.4145, 0.2156]])

In [47]:
print(a.view(-1,32))
print(a.size())

tensor([[0.9826, 0.7057, 0.4725, 0.5816, 0.1636, 0.2196, 0.8620, 0.4628, 0.6589,
         0.4870, 0.9997, 0.5431, 0.7703, 0.2417, 0.3230, 0.6452, 0.5115, 0.5316,
         0.7312, 0.6976, 0.4326, 0.5961, 0.5460, 0.3598, 0.4004, 0.4848, 0.0859,
         0.1078, 0.2560, 0.1734, 0.7836, 0.5910],
        [0.4561, 0.6876, 0.0162, 0.1736, 0.4072, 0.4348, 0.3791, 0.9949, 0.6514,
         0.0893, 0.0150, 0.7559, 0.6124, 0.8414, 0.7062, 0.7631, 0.7246, 0.1353,
         0.6749, 0.0330, 0.7088, 0.1843, 0.4360, 0.4048, 0.9638, 0.7500, 0.8151,
         0.9616, 0.0503, 0.0070, 0.4145, 0.2156]])
torch.Size([8, 8])


In [48]:
a = a.view(-1,32)
print(a)
print(a.size())

tensor([[0.9826, 0.7057, 0.4725, 0.5816, 0.1636, 0.2196, 0.8620, 0.4628, 0.6589,
         0.4870, 0.9997, 0.5431, 0.7703, 0.2417, 0.3230, 0.6452, 0.5115, 0.5316,
         0.7312, 0.6976, 0.4326, 0.5961, 0.5460, 0.3598, 0.4004, 0.4848, 0.0859,
         0.1078, 0.2560, 0.1734, 0.7836, 0.5910],
        [0.4561, 0.6876, 0.0162, 0.1736, 0.4072, 0.4348, 0.3791, 0.9949, 0.6514,
         0.0893, 0.0150, 0.7559, 0.6124, 0.8414, 0.7062, 0.7631, 0.7246, 0.1353,
         0.6749, 0.0330, 0.7088, 0.1843, 0.4360, 0.4048, 0.9638, 0.7500, 0.8151,
         0.9616, 0.0503, 0.0070, 0.4145, 0.2156]])
torch.Size([2, 32])


In [49]:
a.numel() # For number of elements in the tensor

64

In [50]:
print(a.T)
print(a.t())
print((a.t()!=a.T).sum()) # If 0, it means they are equal
# Both print transpose

tensor([[0.9826, 0.4561],
        [0.7057, 0.6876],
        [0.4725, 0.0162],
        [0.5816, 0.1736],
        [0.1636, 0.4072],
        [0.2196, 0.4348],
        [0.8620, 0.3791],
        [0.4628, 0.9949],
        [0.6589, 0.6514],
        [0.4870, 0.0893],
        [0.9997, 0.0150],
        [0.5431, 0.7559],
        [0.7703, 0.6124],
        [0.2417, 0.8414],
        [0.3230, 0.7062],
        [0.6452, 0.7631],
        [0.5115, 0.7246],
        [0.5316, 0.1353],
        [0.7312, 0.6749],
        [0.6976, 0.0330],
        [0.4326, 0.7088],
        [0.5961, 0.1843],
        [0.5460, 0.4360],
        [0.3598, 0.4048],
        [0.4004, 0.9638],
        [0.4848, 0.7500],
        [0.0859, 0.8151],
        [0.1078, 0.9616],
        [0.2560, 0.0503],
        [0.1734, 0.0070],
        [0.7836, 0.4145],
        [0.5910, 0.2156]])
tensor([[0.9826, 0.4561],
        [0.7057, 0.6876],
        [0.4725, 0.0162],
        [0.5816, 0.1736],
        [0.1636, 0.4072],
        [0.2196, 0.4348],
        [0.

### Dot Products and Mult Operations

In [51]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [52]:
x.mul(y) #x*y

tensor([12., 20., 30.])

In [53]:
x*y

tensor([12., 20., 30.])

In [54]:
x.dot(y) ### 3*4+5*4+6*5 = 12 + 20 + 30 = 62

tensor(62.)

In [55]:
torch.dot(x,y)

tensor(62.)

In [56]:
x.dot(y).sum()

tensor(62.)

In [57]:
# Matrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [58]:
print(x)
print(y)

tensor([[1., 4., 2.],
        [1., 5., 5.]])
tensor([[ 5.,  7.],
        [ 8.,  6.],
        [ 9., 11.]])


In [59]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [60]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [61]:
x@y

tensor([[55., 53.],
        [90., 92.]])

In [62]:
x.matmul(y)

tensor([[55., 53.],
        [90., 92.]])

### CPU and GPU

In [63]:
torch.cuda.is_available() # Checks if GPU is available in your machine

False

In [64]:
torch.has_mps

True

In [65]:
#If cuda is True
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.rand(5, device=device) # Will store the tensor in the GPU
    
    # For changing location from CPU to GPU
    y = torch.rand(5) # Creates a tensor in the CPU
    y = y.to(device) # Shifts it to GPU

    z = x * y # z will be a tensor in the GPU as x and y are in the GPU
    # z.numpy() would return an error as z will be in the GPU
    z = z.to('cpu')
    a = z.numpy() # This will work

In [67]:
#If mps is true for Mac M1 chip
if torch.has_mps:
    device = torch.device("mps")
    x = torch.rand(5, device=device) # Will store the tensor in the GPU
    
    # For changing location from CPU to GPU
    y = torch.rand(5) # Creates a tensor in the CPU
    y = y.to(device) # Shifts it to GPU

    z = x * y # z will be a tensor in the GPU as x and y are in the GPU
    # z.numpy() would return an error as z will be in the GPU
    z = z.to('cpu')
    a = z.numpy() # This will work

RuntimeError: The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`